type: 'evidential'
backbone: 'lss'
dataset: 'nuscenes'
logdir: 'outputs/nuscenes/lss_evidential'
gpus: [7]
batch_size: 32
num_workers: 32
weight_decay: 0.0000001
learning_rate: 0.001
num_epochs: 10
loss: ce